from Actions import Key
from rules.ContextualRule import makeContextualRule
from requirements.Emacs import IsEmacs
from requirements.ModeRequirement import ModeRequirement
from rules.emacs.common import emacsExtras, emacsDefaults
from rules.emacs.Cmd import Cmd
from rules.emacs.Keywords import KeywordRule

_mapping = {
    "send funk"   : Key("ca-x"),
    "send buff"   : Key("c-c,c-c"),
    "send region" : Key("c-c,c-r"),
    "interpreter" : Key("c-c,c-z"),
}

JuliaRule = makeContextualRule("Julia", _mapping, emacsExtras, emacsDefaults)
JuliaRule.context.addRequirement(IsEmacs)
JuliaRule.context.addRequirement(ModeRequirement(modes=["julia-mode", "inferior-julia-mode"]))

keywords = [
    "if",
    "else",
    "elseif",
    "while",
    "for",
    "begin",
    "end",
    "quote",
    "try",
    "catch",
    "return",
    "local",
    "function",
    "macro",
    "ccall",
    "finally",
    "break",
    "continue",
    "global",
    "where",
    "module",
    "using",
    "import",
    "export",
    "const",
    "let",
    "do",
    "in",
    "baremodule",
    "importall",
    "immutable",
    "type",
    "bitstype",
    "abstract",
    "typealias" ,
    "primitive ",
    "struct",
    "mutable",
    "Number",
    "Real",
    "BigInt",
    "Integer",
    "UInt",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "UInt128",
    "Int",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "Int128",
    "BigFloat",
    "AbstractFloat",
    "Float16",
    "Float32",
    "Float64",
    "Complex128",
    "Complex64",
    "Bool",
    "Cuchar",
    "Cshort",
    "Cushort",
    "Cint",
    "Cuint",
    "Clonglong",
    "Culonglong",
    "Cintmax_t",
    "Cuintmax_t",
    "Cfloat",
    "Cdouble",
    "Cptrdiff_t",
    "Cssize_t",
    "Csize_t",
    "Cchar",
    "Clong",
    "Culong",
    "Cwchar_t",
    "Char",
    "String",
    "SubString",
    "Array",
    "DArray",
    "AbstractArray",
    "AbstractVector",
    "AbstractMatrix",
    "AbstractSparseMatrix",
    "SubArray",
    "StridedArray",
    "StridedVector",
    "StridedMatrix",
    "VecOrMat",
    "StridedVecOrMat",
    "DenseArray",
    "SparseMatrixCSC",
    "BitArray",
    "Range",
    "OrdinalRange",
    "StepRange",
    "UnitRange",
    "FloatRange",
    "Tuple",
    "NTuple",
    "Vararg",
    "DataType",
    "Symbol",
    "Function",
    "Vector",
    "Matrix",
    "Union",
    "Type",
    "Any",
    "Complex",
    "AbstractString",
    "Ptr",
    "Void",
    "Exception",
    "Task",
    "Signed",
    "Unsigned",
    "Associative",
    "Dict",
    "IO",
    "IOStream",
    "Rational",
    "Regex",
    "RegexMatch",
    "Set",
    "IntSet",
    "Expr",
    "WeakRef",
    "ObjectIdDict",
    "AbstractRNG",
    "MersenneTwister"
    ]

JuliaKeywordRule = KeywordRule(["julia-mode", "inferior-julia-mode"], keywords)
