from Actions import Text
from rules.SeriesMappingRule import SeriesMappingRule
from rules.emacs.Emacs import Emacs
from rules.emacs.Text import EmacsText
from rules.emacs.Cmd import runEmacsCmd, Cmd
from rules.Rule import registerRule
from rules.emacs.Base import EmacsBase

@registerRule
class Lisp(EmacsBase):
    majorMode = "emacs-lisp-mode"
    
    keywords = [
        "and",
        ["aref", "A ref"],
        "car",
        "catch",
        ["cdr", "cooder"],
        "concat",
        ["cond", "conned"],
        "condition-case",
        "cons",
        "defadvice",
        "defconst",
        "defmacro",
        "defstruct",
        "defun",
        "defvar",
        "defvar-local",
        ["delq", "del Q"],
        "dolist",
        "dotimes",
        ["eq", "E Q"],
        "equal",
        "eval",
        "format",
        "function",
        "funcall",
        "gensym",
        "goto-char",
        "identity",
        "if",
        ["incf", "ink F"],
        "interactive",
        "lambda",
        "let",
        "length",
        "loop",
        "nil",
        "map",
        "mapcar",
        "mapconcat",
        "member",
        ["memq", "mem Q"],
        "message",
        "not",
        ["nth", "enth"],
        "null",
        "optional",
        "or",
        "point",
        "push",
        "prog1",
        "prog2",
        "progn",
        "provide",
        ["remq", "rem Q"],
        "require",
        "rest",
        "quote",
        "save-current-buffer",
        "save-excursion",
        "save-match-data",
        "save-restriction",
        "setcar",
        ["setq", "set Q"],
        ["setq-default", "set Q default"],
        "subseq",
        "throw",
        "track-mouse",
        "unless",
        "unwind-protect",
        "with-current-buffer",
        "with-selected-frame",
        "with-selected-window",
        "when",
        "while",
    ]
