#!/usr/bin/env python
# -*- coding: utf-8 -*-

from Actions import Key
from rules.ContextualRule import makeContextualRule
from requirements.Emacs import IsEmacs
from requirements.ModeRequirement import ModeRequirement
from rules.emacs.common import emacsExtras, emacsDefaults
from rules.emacs.Cmd import Cmd
from rules.emacs.Keywords import KeywordRule

keywords = [
    "say",
    "Any",
    "Cool",
    ["Str", "stir"],
    ["Int", "integer"],
    ["Rat", "rational"],
    "bool",
    "True",
    "False",
    "Nil",
    "if",
    ["elsif", "else if"],
    "else",
    "my",
    "unless",
    "with",
    "without",
    "for",
    "given",
    "when",
    "default",
    "proceed",
    "loop",
    "print",
    "get",
    "prompt",
    "run",
    "shell",
    "slurp",
    "spurt",
    "role",
    "sub",
    "put",
    "note",
    ["dd", "Dee Dee"],
    "open",
    "multi",
    "return",
    "class",
    "has",
    "method",
    ["readonly", "read only"],
    "is",
    "submethod",
    "does",
    "CATCH",
    "WHAT",
    "HOW",
    "try",
    "die",
    "regex",
    "await",
    "race",
    "hyper",
    "start",
    "so",
    "copy",
    "next",
    "redo",
    "last",
    ["eq", "E Q"],
    ["nq", "N Q"],
    ["eqv", "equivalent"],
    ["$_", "topic"],
    "do",
    "gather",
    "where",
    "BUILD",
    "CONTROL",
    "module",
    "unit",
    "grammar",
    "our",
    "constant",
    "state",
    ["BEGIN", "begin"],
    ["CHECK", "check"],
    ["INIT", "init"],
    ["END", "end"],
    ["PRE", "pre"],
    ["POST", "post"],
    ["COMPOSE", "compose"],
    ["KEEP", "keep"],
    ["UNDO", "undo"],
    "take",
    "eager",
    "sink",
    "prefix",
    "postfix",
    "infix",
    "circumfix",
    "postcircumfix",
    "leg",
    "before",
    "after",
    "set",
    "augment",
    "but",
    "supersede",
    "temp",
    "let",
    ["SetHash", "set hash"],
    "dir",
    ["chdir", "change dir"],
    "use",
    "self",
    "also"
]

P6KeywordRule = KeywordRule("perl6-mode", keywords)
